### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by joetidee** [saucelabs/sauce-cypress-runner#119]
Came here for this page:
https://docs.saucelabs.com/testrunner-toolkit/index.html?mkt_tok=NDY4LVhCVC02ODcAAAF7wJx-LncwaVv2b8O3EBp1cA0CUud0X1BZWtQLDhrMEOS_u3U5bc3fmGP2W2EpfO6KkxbyHK3fDQCwb1c2SbHvDrdtHzxvTvHP_OXiMFm_gBuFAg

Suggests that the browser support is dictated by the docker image. So just wondered what browsers (both mobile and desktop) this image supports.

**Comment by alexplischke** [comment]
It's noted as part of the release notes :) --> https://github.com/saucelabs/sauce-cypress-runner/releases/tag/v6.0.1
